### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tlove004**
Deliverables == what we will be turning in??
Moved prior deliverables to be the why should anyone care part.

### CODE REVIEW

**Comment by tlove004** [comment]
What you guys think?

**Comment by jgome043** [comment]
"looks good, what's your name?"

**Comment by phangjohn27** [comment]
looooks goood :3

**Comment by nwillhite** [comment]
looks good, looks good!

**Comment by jgome043** [comment]
Approved by majority.

**Pull request merged**
